// data.js

export const TABS = [
    {
      label: "All",
      value: "all",
    },
    {
      label: "Manager",
      value: "Manager",
    },
    {
      label: "Programator",
      value: "Programator",
    },
    {
        label: "Executive",
        value: "Executive",
      },
  ];
  
  export const TABLE_HEAD = ["Member", "Function", "Status", "Employed", ""];
  
  export const TABLE_ROWS = [
    {
      img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-3.jpg",
      name: "John Michael",
      email: "john@creative-tim.com",
      job: "Manager",
      org: "Organization",
      online: true,
      date: "23/04/18",
    },
    {
        img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-2.jpg",
        name: "Alexa Liras",
        email: "alexa@creative-tim.com",
        job: "Programator",
        org: "Developer",
        online: false,
        date: "23/04/18",
      },
      {
        img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-1.jpg",
        name: "Laurent Perrier",
        email: "laurent@creative-tim.com",
        job: "Executive",
        org: "Projects",
        online: false,
        date: "19/09/17",
      },
      {
        img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-4.jpg",
        name: "Michael Levi",
        email: "michael@creative-tim.com",
        job: "Programator",
        org: "Developer",
        online: true,
        date: "24/12/08",
      },
      {
        img: "https://demos.creative-tim.com/test/corporate-ui-dashboard/assets/img/team-6.jpg",
        name: "David Smith",
        email: "david@creative-tim.com",
        job: "Manager",
        org: "Executive",
        online: true,
        date: "10/05/24",
      },
      {
        img: "https://randomuser.me/api/portraits/men/1.jpg",
        name: "Daniel Brown",
        email: "daniel@creative-tim.com",
        job: "Developer",
        org: "Tech",
        online: false,
        date: "05/18/23",
      },
      {
        img: "https://randomuser.me/api/portraits/women/2.jpg",
        name: "Sophia Miller",
        email: "sophia@creative-tim.com",
        job: "Designer",
        org: "Creative",
        online: true,
        date: "09/21/22",
      },
      {
        img: "https://randomuser.me/api/portraits/men/3.jpg",
        name: "Matthew Wilson",
        email: "matthew@creative-tim.com",
        job: "Manager",
        org: "Operations",
        online: true,
        date: "11/30/20",
      },
      {
        img: "https://randomuser.me/api/portraits/women/4.jpg",
        name: "Emma Thompson",
        email: "emma@creative-tim.com",
        job: "Analyst",
        org: "Data",
        online: false,
        date: "07/12/21",
      },
      {
        img: "https://randomuser.me/api/portraits/men/5.jpg",
        name: "Ryan Garcia",
        email: "ryan@creative-tim.com",
        job: "Engineer",
        org: "Tech",
        online: true,
        date: "03/05/24",
      },
      {
        img: "https://randomuser.me/api/portraits/women/6.jpg",
        name: "Olivia Evans",
        email: "olivia@creative-tim.com",
        job: "Project Manager",
        org: "Projects",
        online: false,
        date: "06/18/22",
      },
      {
        img: "https://randomuser.me/api/portraits/men/7.jpg",
        name: "Noah Martinez",
        email: "noah@creative-tim.com",
        job: "Developer",
        org: "Tech",
        online: true,
        date: "02/07/23",
      },
      {
        img: "https://randomuser.me/api/portraits/women/8.jpg",
        name: "Isabella Thompson",
        email: "isabella@creative-tim.com",
        job: "Designer",
        org: "Creative",
        online: false,
        date: "08/11/21",
      },
      {
        img: "https://randomuser.me/api/portraits/men/9.jpg",
        name: "Ethan White",
        email: "ethan@creative-tim.com",
        job: "Manager",
        org: "Operations",
        online: true,
        date: "12/03/20",
      },
      {
        img: "https://randomuser.me/api/portraits/women/10.jpg",
        name: "Ava Moore",
        email: "ava@creative-tim.com",
        job: "Analyst",
        org: "Data",
        online: false,
        date: "10/17/22",
      }  
  ];
  